### ISSUE TITLE
No module named 'hypexport'

### ISSUE THREAD

**Issue by AdelleBernal** [karlicoss/hypexport#9]
Hi! I want to use hypothesis module with orger.
I run first: `pip3 install --user git+https://github.com/karlicoss/hypexport`
Then  I create secrets.py containing my username and token.
Then I run `python3 -m hypexport.export --secrets /path/to/secrets.py`

However, I get:
`/usr/local/anaconda3/bin/python3: Error while finding module specification for 'hypexport.export' (ModuleNotFoundError: No module named 'hypexport')
`

**Comment by AdelleBernal** [comment]
I managed to get until here:

```bash
hpi doctor my.hypothesis                                                                    ✔  52s   16:44:31  
✅ import order: ['/Users/user/.local/lib/python3.6/site-packages/my']
✅ config file : /Users/user/Library/Application Support/my/my/config/__init__.py
✅ syntax check: /usr/local/anaconda3/bin/python3 -m compileall /Users/user/Library/Application Support/my/my/config/__init__.py
❗ mypy not found, so can't check config with it. See https://github.com/python/mypy#readme if you want to install it and retry
✅ config check: success!
❌ FAIL: my.hypothesis                                      loading failed
   Traceback (most recent call last):
     File "/Users/user/.local/lib/python3.6/site-packages/my/core/__main__.py", line 241, in modules_check
       mod = importlib.import_module(m)
     File "/usr/local/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
       return _bootstrap._gcd_import(name[level:], package, level)
     File "<frozen importlib._bootstrap>", line 994, in _gcd_import
     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
     File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
     File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
     File "/Users/user/.local/lib/python3.6/site-packages/my/hypothesis.py", line 39, in <module>
       dal = pre_pip_dal_handler('hypexport', e, config, requires=REQUIRES)
     File "/Users/user/.local/lib/python3.6/site-packages/my/core/compat.py", line 49, in pre_pip_dal_handler
       raise e
     File "/Users/user/.local/lib/python3.6/site-packages/my/hypothesis.py", line 36, in <module>
       from hypexport import dal
   ModuleNotFoundError: No module named 'hypexport'

```
